### ISSUE TITLE
error in cmakeLists.txt

### ISSUE THREAD

**Issue by raja890** [gaowenliang/sgbm_ros#1]
what is  include(/home/nvidia/lib/opencv_arm/OpenCVConfig.cmake) in your cmakeLists.txt where to find it

**Comment by gaowenliang** [comment]
I did not use the opencv from apt-get. I build an opencv library locally. And that line: " include(/home/nvidia/lib/opencv_arm/OpenCVConfig.cmake) " is to find the locally Opencv. You can use #find_package( OpenCV REQUIRED)
 to find the build in OpenCV instead of that line.

**Comment by raja890** [comment]
Thanks , I get that.
